/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tugasakhirlibrary.mavenproject1.viewLayer;

import javax.swing.*;
import java.awt.event.ActionListener;


/**
 *
 * @author ASUS ROG
 */
public class LoginWindow extends javax.swing.JFrame {

    /**
     * Creates new form LoginWindow
     */
    public LoginWindow(boolean visible) {
        initComponents();
        setVisible(visible);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tUser = new javax.swing.JTextField();
        tPass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        bLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lSignUp = new javax.swing.JLabel();
        lReset = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(720, 480));
        setMinimumSize(new java.awt.Dimension(720, 480));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(24, 12, 59));
        jPanel1.setLayout(null);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\kraun\\OneDrive\\Documents\\archivenandatugas\\SEMESTER 3\\Praktikum OOP - PBO\\Pertemuan TB\\library-game-management\\mavenproject1\\src\\main\\java\\com\\tugasakhirlibrary\\mavenproject1\\viewLayer\\defaultuser.png")); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(490, 90, 96, 93);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome!");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(490, 50, 87, 24);

        tUser.setBackground(new java.awt.Color(153, 153, 153));
        tUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tUserKeyPressed(evt);
            }
        });
        jPanel1.add(tUser);
        tUser.setBounds(449, 196, 167, 37);

        tPass.setBackground(new java.awt.Color(153, 153, 153));
        tPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tPassKeyPressed(evt);
            }
        });
        jPanel1.add(tPass);
        tPass.setBounds(449, 251, 167, 37);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Forget Password?");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(450, 290, 130, 16);

        bLogin.setBackground(new java.awt.Color(51, 153, 0));
        bLogin.setForeground(new java.awt.Color(255, 255, 255));
        bLogin.setText("Login");
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });
        jPanel1.add(bLogin);
        bLogin.setBounds(500, 330, 73, 27);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Don't have an account?");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(480, 360, 150, 16);

        lSignUp.setForeground(new java.awt.Color(0, 204, 51));
        lSignUp.setText("Sign up");
        lSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lSignUpMouseClicked(evt);
            }
        });
        jPanel1.add(lSignUp);
        lSignUp.setBounds(510, 380, 80, 16);

        lReset.setForeground(new java.awt.Color(0, 204, 51));
        lReset.setText("Reset");
        lReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lResetMouseClicked(evt);
            }
        });
        jPanel1.add(lReset);
        lReset.setBounds(580, 290, 34, 16);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\kraun\\OneDrive\\Documents\\archivenandatugas\\SEMESTER 3\\Praktikum OOP - PBO\\Pertemuan TB\\library-game-management\\mavenproject1\\src\\main\\java\\com\\tugasakhirlibrary\\mavenproject1\\viewLayer\\Component\\resizedbackground.png")); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 660, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lSignUpMouseClicked
        // TODO add your handling code here:
        new RegisterWindow(true);
        this.setVisible(false);
    }//GEN-LAST:event_lSignUpMouseClicked

    private void lResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lResetMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lResetMouseClicked

    public void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        // TODO add your handling code here:
        new HomeWindow(getTuser()).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bLoginActionPerformed

    private void tUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tUserKeyPressed
        // TODO add your handling code here:
        getTuser();
    }//GEN-LAST:event_tUserKeyPressed

    private void tPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tPassKeyPressed
        // TODO add your handling code here:
        getTpass();
    }//GEN-LAST:event_tPassKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginWindow(true);
            }
        });
    }

    //method mendapatkan string dari textfield
    public String getTuser() {
        return tUser.getText();
    }
    public String getTpass() {
        return tPass.getText();
    }
    public void SubmitUser(ActionListener actionListener) {
        bLogin.addActionListener(actionListener);
        System.out.println("kajfgajksdghajdgas");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lReset;
    private javax.swing.JLabel lSignUp;
    private javax.swing.JPasswordField tPass;
    private javax.swing.JTextField tUser;
    // End of variables declaration//GEN-END:variables
}
